language: python
python:
  - 2.6
  - 2.7
  - 3.5
install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libhdf5-serial-dev
  - wget http://salilab.org/modeller/9.17/modeller_9.17-1_amd64.deb
  - sudo dpkg -i modeller_9.17-1_amd64.deb
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
# Need valid Modeller license key to run test suite
#ctest --output-on-failure
