sudo: required
dist: trusty
language: python
python:
  - 2.6
  - 2.7
  - 3.5
install:
  - wget -q $LICENSE_URL -O mod-license >& /dev/null
  - sudo apt-get -qq update
  - sudo apt-get install -y swig
  - wget http://salilab.org/modeller/9.17/modeller_9.17-1_amd64.deb
  - KEY_MODELLER=`cat mod-license` sudo dpkg -i modeller_9.17-1_amd64.deb
  - ln -sf /usr/lib/python$TRAVIS_PYTHON_VERSION/dist-packages/_modeller.so $(dirname $(which python))/../lib/*/site-packages/
  - ln -sf /usr/lib/python$TRAVIS_PYTHON_VERSION/dist-packages/modeller $(dirname $(which python))/../lib/*/site-packages/
  - wget http://salilab.org/modeller/downloads/hdf5-1.8.16-headers-64bit-ubuntu.tar.gz
  - tar -xzf hdf5-1.8.16-headers-64bit-ubuntu.tar.gz && mv hdf5-1.8.16-headers-64bit-ubuntu hdf5-inc
  - export CMAKE_INCLUDE_PATH=`pwd`/hdf5-inc
  - mkdir hdf5-libs
  - ln -sf /usr/lib/modeller9.17/lib/x86_64-intel8/libhdf5_hl.so.10 hdf5-libs/libhdf5_hl.so
  - ln -sf /usr/lib/modeller9.17/lib/x86_64-intel8/libhdf5.so.10 hdf5-libs/libhdf5.so
  - export CMAKE_LIBRARY_PATH=`pwd`/hdf5-libs
  - pip install coverage
script:
  - mkdir build
  - cd build
  - ../tools/coverage/setup.py
  - PYTHON_INC=$(echo $(dirname $(which python))/../include/*/)
  - PYTHON_LIB=$(echo /opt/python/${TRAVIS_PYTHON_VERSION}.*/lib/libpython${TRAVIS_PYTHON_VERSION}*.so)
  - PYTHONPATH=`pwd`/coverage cmake .. -DCMAKE_BUILD_TYPE=Debug -DPYTHON_INCLUDE_DIR=$PYTHON_INC -DPYTHON_LIBRARY=$PYTHON_LIB -DCMAKE_C_FLAGS="-fprofile-arcs -ftest-coverage"
  - rm ../src/mdt_config.h
  - make
  - ctest --output-on-failure
after_success:
  - (cd coverage && coverage combine && mv .coverage ..)
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    secure: "b/cP+uy/Ay0r3bvUlxHWug3vzoSJuGPhZ24/5m53YvNEoLn/N+x/9ijpIvM1lonLy7d1tVLazKZku3VxxNwlS4wq+Q83LmfOF3kCq/I7pQ0DdSz5Jk7uamQLtTH6Bq86iofBWIrF7PzeE6mZA3ZGvS60A6Zu43zRaGXjFGw5DamO4Sku7c94L+Gus0b9ljP7EGSONOZhwJZf0KKvuhIjjANN9mZ9ZgOC+wvaQ9oJKkb02Pz/fXE0lDxmy5WQYh17oz251Rw/7FxajMqgnTUrqIClUSeN4Xw0xMwtMdrXL/xK7xdUbS24yhjwpqnrzscdwfVSaL0tWxOAwKNjROEM8gM7ze0z3NStAZBAuhRTAKjq9xcZS+ozAEWJzKKS463XZYjuigHIyMUUm0+q/OQj7xEaJyg6Sr2zwOPTcP4EjaBhCNCZ69YJ4+gJ17bUbNwQQMYWehVU6NNqE+Jq4jR8T2jxKGJ0J8OqbDCrCF6JMgmHgiWnjApBKR3WAwSUK7Sr2bHZPHmT8zlGw+oTyFTGKfStqOOUjq9QXn3pm++4CBko9KoBt1NP7KNJDblWXxd6lqwgLLDzdwmpNI8T6prFV4avsacnLHdjBFt/mKy009KtJlvHxLEpmpD2LX4PelGoiyXd4fbjjOQKjZsyxPD8xlcwVHXhi0yMlyqQuYLCP0U="
