language: python
python:
  - 2.6
  - 2.7
  - 3.5
install:
  - wget -q $LICENSE_URL -O mod-license >& /dev/null
  - sudo apt-get -qq update
  - sudo apt-get install -y libhdf5-serial-dev swig
  - wget http://salilab.org/modeller/9.17/modeller_9.17-1_amd64.deb
  - KEY_MODELLER=`cat mod-license` sudo dpkg -i modeller_9.17-1_amd64.deb
  - ln -sf /usr/lib/python$TRAVIS_PYTHON_VERSION/dist-packages/_modeller.so $(dirname $(which python))/../lib/*/site-packages/
  - ln -sf /usr/lib/python$TRAVIS_PYTHON_VERSION/dist-packages/modeller $(dirname $(which python))/../lib/*/site-packages/
script:
  - mkdir build
  - cd build
  - PYTHON_INC=$(echo $(dirname $(which python))/../include/*/)
  - PYTHON_LIB=$(echo /opt/python/${TRAVIS_PYTHON_VERSION}.*/lib/libpython${TRAVIS_PYTHON_VERSION}*.so)
  - cmake .. -DPYTHON_INCLUDE_DIR=$PYTHON_INC -DPYTHON_LIBRARY=$PYTHON_LIB
  - make
  - ln -sf __mdt.so pyext/_mdt.so
  - ctest --output-on-failure
env:
  global:
    secure: "b/cP+uy/Ay0r3bvUlxHWug3vzoSJuGPhZ24/5m53YvNEoLn/N+x/9ijpIvM1lonLy7d1tVLazKZku3VxxNwlS4wq+Q83LmfOF3kCq/I7pQ0DdSz5Jk7uamQLtTH6Bq86iofBWIrF7PzeE6mZA3ZGvS60A6Zu43zRaGXjFGw5DamO4Sku7c94L+Gus0b9ljP7EGSONOZhwJZf0KKvuhIjjANN9mZ9ZgOC+wvaQ9oJKkb02Pz/fXE0lDxmy5WQYh17oz251Rw/7FxajMqgnTUrqIClUSeN4Xw0xMwtMdrXL/xK7xdUbS24yhjwpqnrzscdwfVSaL0tWxOAwKNjROEM8gM7ze0z3NStAZBAuhRTAKjq9xcZS+ozAEWJzKKS463XZYjuigHIyMUUm0+q/OQj7xEaJyg6Sr2zwOPTcP4EjaBhCNCZ69YJ4+gJ17bUbNwQQMYWehVU6NNqE+Jq4jR8T2jxKGJ0J8OqbDCrCF6JMgmHgiWnjApBKR3WAwSUK7Sr2bHZPHmT8zlGw+oTyFTGKfStqOOUjq9QXn3pm++4CBko9KoBt1NP7KNJDblWXxd6lqwgLLDzdwmpNI8T6prFV4avsacnLHdjBFt/mKy009KtJlvHxLEpmpD2LX4PelGoiyXd4fbjjOQKjZsyxPD8xlcwVHXhi0yMlyqQuYLCP0U="
