sudo: required
dist: xenial
language: python
python:
  - 2.7
  - 3.6
  - 3.7
install:
  - wget -q $LICENSE_URL -O mod-license >& /dev/null
  - tools/travis/install_deps.sh $TRAVIS_PYTHON_VERSION `pwd`/mod-license 
  - export CMAKE_INCLUDE_PATH=`pwd`/hdf5-inc
  - export CMAKE_LIBRARY_PATH=`pwd`/hdf5-libs
  - pip install coverage
script:
  - mkdir build
  - cd build
  - ../tools/coverage/setup.py
  - PYTHON_EXE=$(which python)
  - PYTHON_INC=$(echo $(dirname $(which python))/../include/*/)
  - PYTHON_LIB=$(echo /opt/python/${TRAVIS_PYTHON_VERSION}.*/lib/libpython${TRAVIS_PYTHON_VERSION}*.so)
  - PYTHONPATH=`pwd`/coverage cmake .. -DCMAKE_BUILD_TYPE=Debug -DPYTHON_EXECUTABLE=$PYTHON_EXE -DPYTHON_INCLUDE_DIR=$PYTHON_INC -DPYTHON_LIBRARY=$PYTHON_LIB -DCMAKE_C_FLAGS="-fprofile-arcs -ftest-coverage"
  - rm ../src/mdt_config.h
  - make
  - ctest --output-on-failure
after_success:
  - (cd coverage && coverage combine && mv .coverage ..)
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    secure: "b/cP+uy/Ay0r3bvUlxHWug3vzoSJuGPhZ24/5m53YvNEoLn/N+x/9ijpIvM1lonLy7d1tVLazKZku3VxxNwlS4wq+Q83LmfOF3kCq/I7pQ0DdSz5Jk7uamQLtTH6Bq86iofBWIrF7PzeE6mZA3ZGvS60A6Zu43zRaGXjFGw5DamO4Sku7c94L+Gus0b9ljP7EGSONOZhwJZf0KKvuhIjjANN9mZ9ZgOC+wvaQ9oJKkb02Pz/fXE0lDxmy5WQYh17oz251Rw/7FxajMqgnTUrqIClUSeN4Xw0xMwtMdrXL/xK7xdUbS24yhjwpqnrzscdwfVSaL0tWxOAwKNjROEM8gM7ze0z3NStAZBAuhRTAKjq9xcZS+ozAEWJzKKS463XZYjuigHIyMUUm0+q/OQj7xEaJyg6Sr2zwOPTcP4EjaBhCNCZ69YJ4+gJ17bUbNwQQMYWehVU6NNqE+Jq4jR8T2jxKGJ0J8OqbDCrCF6JMgmHgiWnjApBKR3WAwSUK7Sr2bHZPHmT8zlGw+oTyFTGKfStqOOUjq9QXn3pm++4CBko9KoBt1NP7KNJDblWXxd6lqwgLLDzdwmpNI8T6prFV4avsacnLHdjBFt/mKy009KtJlvHxLEpmpD2LX4PelGoiyXd4fbjjOQKjZsyxPD8xlcwVHXhi0yMlyqQuYLCP0U="
