files = ['xray.c', 'radius_gyration.c', 'residue_accessibility.c',
         'atom_accessibility.c', 'fractional_atom_accessibility.c',
         'atom_type.c', 'atom_hydrogen_bonds.c', 'hydrogen_bond_satisfaction.c',
         'tuple_type.c', 'tuple_distance.c', 'atom_distance.c', 'tuple_angle.c',
         'tuple_dihedral.c', 'bond_type.c', 'bond_length.c', 'angle.c',
         'dihedral.c', 'sequence_length.c']

files = [File(x) for x in files]
Return('files')
