files = ['xray.c', 'radius_gyration.c', 'residue_accessibility.c',
         'atom_accessibility.c', 'fractional_atom_accessibility.c',
         'atom_type.c']

files = [File(x) for x in files]
Return('files')
