Import('env')

# Source files
files = ['anggrp.lib', 'bndgrp.lib', 'impgrp.lib', 'trpcls.lib', 'dblcls.lib',
         'atmcls-hbda.lib']

# Install the files
inst = env.Install(env['destdir'] + env['datadir'], files)
env.Alias('install', inst)
