Import('env', 'modconfig')

# Source files
files = ['anggrp.lib', 'bndgrp.lib', 'impgrp.lib', 'trpcls.lib', 'dblcls.lib',
         'atmcls-hbda.lib', 'mdt.bin']

# Install the files
inst = env.Install(modconfig['modlib'], files)
env.Alias('install', inst)
