import os.path

Import('env', 'bin', 'pyext')

docbook = env.DocBook("index.html", "../manual.xml",
                      DOCBOOK_FRAGMENT=File('../html-style.xml'))
epydoc = env.Epydoc('epydoc/index.html', (bin, pyext))

docdir = env['docdir']
env.DocBookInstall(os.path.join(docdir, 'index.html'), docbook)
env.Install(docdir, 'mdt.css')
env.Alias('docinstall', docdir)

docdir = os.path.join(docdir, 'epydoc')
env.EpydocInstall(os.path.join(docdir, 'index.html'), epydoc)

# Subdirectories:
SConscript('pdf/SConscript')
