name: build

on: [push, pull_request]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      env:
        KEY_MODELLER: ${{ secrets.KEY_MODELLER }}
      run: |
        tools/travis/install_deps.sh ${{ matrix.python-version }}
    - name: Test
      run: |
        export CMAKE_INCLUDE_PATH=`pwd`/hdf5-inc
        export CMAKE_LIBRARY_PATH=`pwd`/hdf5-libs
        PYTHON_EXE=$(which python)
        PYTHON_INC=$(echo $(dirname $(which python))/../include/*/)
        PYTHON_LIB=$(echo $(dirname $(which python))/../lib/libpython${{ matrix.python-version }}*.so)
        mkdir build && cd build
        ../tools/coverage/setup.py
        PYTHONPATH=`pwd`/coverage cmake .. -DCMAKE_BUILD_TYPE=Debug -DPYTHON_EXECUTABLE=$PYTHON_EXE -DPYTHON_INCLUDE_DIR=$PYTHON_INC -DPYTHON_LIBRARY=$PYTHON_LIB -DCMAKE_C_FLAGS="-fprofile-arcs -ftest-coverage"
        mv ../src/mdt_config.h ../src/mdt_config.h.bkp
        make
        cd ..
        PYTHONPATH=build/coverage:build/pyext:pyext:$PYTHONPATH py.test --cov=pyext --cov-branch --cov-report=xml -v test
        flake8 --exclude=constr2005/,doc/,examples=/,tools/,sitecustomize.py,config.py .
        mv src/mdt_config.h.bkp src/mdt_config.h
    - uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
